apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafkagram
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bthode/kafkagram-argocd.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: kafkagram
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
