apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsutils-deployment
  labels:
    app: dnsutils
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dnsutils
  template:
    metadata:
      labels:
        app: dnsutils
    spec:
      containers:
        - name: dnsutils
          image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dnsutils-service
spec:
  type: LoadBalancer
  selector:
    app: dnsutils
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
