apiVersion: apps/v1
kind: Deployment
metadata:
  name: microbot
spec:
  selector:
    matchLabels:
      app: microbot
  replicas: 1
  template:
    metadata:
      labels:
        app: microbot
    spec:
      containers:
      - name: microbot
        image: dontrebootme/microbot
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dnsutils-service
spec:
  type: LoadBalancer
  selector:
    app: dnsutils
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
